from django.urls import path
from . import views

urlpatterns = [
    # [...]
    # En los path colocar int si primary key es numerica, str si pk es alfanumerica (rut)
    path('usuarios/', views.UsuarioList.as_view(), name='usuario_list'),
    path('usuario-create/', views.UsuarioCreate.as_view(), name='usuario_create'),
    path('usuario-update/<int:pk>', views.UsuarioUpdate.as_view(), name='usuario_update'),
    path('usuario-delete/<int:pk>', views.UsuarioDelete.as_view(), name='usuario_delete'),
    #path('usuario-perfil/<int:pk>', views.PerfilUpdate.as_view(), name='usuario_perfil'),
    path('clientes/', views.ClienteList.as_view(), name='cliente_list'),
    path('cliente-create/', views.ClienteCreate.as_view(), name='cliente_create'),
    path('cliente-update/<str:pk>', views.ClienteUpdate.as_view(), name='cliente_update'),
    path('cliente-delete/<str:pk>', views.ClienteDelete.as_view(), name='cliente_delete'),
    path('proveedores/', views.ProveedorList.as_view(), name='proveedor_list'),
    path('proveedor-create/', views.ProveedorCreate.as_view(), name='proveedor_create'),
    path('proveedor-update/<str:pk>', views.ProveedorUpdate.as_view(), name='proveedor_update'),
    path('proveedor-delete/<str:pk>', views.ProveedorDelete.as_view(), name='proveedor_delete'),
    path('platos/', views.PlatoList.as_view(), name='plato_list'),
    path('plato-create/', views.PlatoCreate.as_view(), name='plato_create'),
    path('plato-update/<int:pk>', views.PlatoUpdate.as_view(), name='plato_update'),
    path('plato-delete/<int:pk>', views.PlatoDelete.as_view(), name='plato_delete'),
    path('oc/', views.OrdenCompraList.as_view(), name='oc_list'),
    path('oc-create/', views.OrdenCompraCreate.as_view(), name='oc_create'),
    path('oc-update/<int:pk>', views.OrdenCompraUpdate.as_view(), name='oc_update'),
    path('oc-cancel/<int:pk>', views.OrdenCompraCancel.as_view(), name='oc_cancel'),
    path('oc-delete/<int:pk>', views.OrdenCompraDelete.as_view(), name='oc_delete'),
    path('empleados/', views.EmpleadoList.as_view(), name='empleado_list'),
    path('empleado-create/', views.EmpleadoCreate.as_view(), name='empleado_create'),
    path('empleado-update/<str:pk>', views.EmpleadoUpdate.as_view(), name='empleado_update'),
    path('empleado-delete/<str:pk>', views.EmpleadoDelete.as_view(), name='empleado_delete'),
    path('orden_pedidos/', views.Orden_pedidoList.as_view(), name='orden_pedido_list'),
    path('orden_pedido-create/', views.Orden_pedidoCreate.as_view(), name='orden_pedido_create'),
    path('orden_pedido-update/<str:pk>', views.Orden_pedidoUpdate.as_view(), name='orden_pedido_update'),
    path('orden_pedido-delete/<str:pk>', views.Orden_pedidoDelete.as_view(), name='orden_pedido_delete'),
    path('producto/', views.ProductoList.as_view(), name='producto_list'),
    path('producto-create/', views.ProductoCreate.as_view(), name='producto_create'),
    path('producto-update/<int:pk>', views.ProductoUpdate.as_view(), name='producto_update'),
    path('producto-delete/<int:pk>', views.ProductoDelete.as_view(), name='producto_delete'),
    path('reporte/', views.ReporteList.as_view(), name='reporte_list'),
    path('reporte-create/', views.ReporteCreate.as_view(), name='reporte_create'),
    path('reporte-update/<int:pk>', views.ReporteUpdate.as_view(), name='reporte_update'),
    path('reporte-delete/<int:pk>', views.ReporteDelete.as_view(), name='reporte_delete'),
    path('huesped/', views.HuespedList.as_view(), name='huesped_list'),
    path('huesped-create/', views.HuespedCreate.as_view(), name='huesped_create'),
    path('huesped-update/<str:pk>', views.HuespedUpdate.as_view(), name='huesped_update'),
    path('huesped-delete/<str:pk>', views.HuespedDelete.as_view(), name='huesped_delete'),
    path('habitaciones/', views.HabitacionList.as_view(), name='habitacion_list'),
    path('habitacion-create/', views.HabitacionCreate.as_view(), name='habitacion_create'),
    path('habitacion-update/<int:pk>', views.HabitacionUpdate.as_view(), name='habitacion_update'),
    path('habitacion-delete/<int:pk>', views.HabitacionDelete.as_view(), name='habitacion_delete'),
    path('manual_ayuda', views.manual_ayuda, name='manual_ayuda'),
]
