# Generated by Django 2.2.1 on 2019-05-30 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden_compra',
            fields=[
                ('numero_orden', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_orden', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('rut_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.Cliente')),
            ],
        ),
    ]
