# Generated by Django 2.2.1 on 2019-05-31 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mantenedor', '0002_orden_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rut_proveedor', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('giro', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('numero', models.CharField(max_length=13)),
                ('correo', models.CharField(max_length=30)),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
