# Generated by Django 2.2.1 on 2019-06-01 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mantenedor', '0003_plato_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden_pedido',
            fields=[
                ('id_orden_pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField()),
                ('fecha_recepcion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('stock_critico', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('id_orden_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.Orden_pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('run_empleado', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=1)),
                ('telefono_movil', models.CharField(max_length=12)),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
