# Generated by Django 2.2.1 on 2019-06-30 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0005_remove_proveedor_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden_pedido',
            name='rut_proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mantenedor.Proveedor'),
            preserve_default=False,
        ),
    ]
