# Generated by Django 2.2.1 on 2019-06-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0006_orden_pedido_rut_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden_compra',
            name='estado',
            field=models.CharField(choices=[('A', 'Activa'), ('C', 'Cancelada')], default='A', max_length=1),
        ),
    ]
