# Generated by Django 2.2.1 on 2019-07-01 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0007_orden_compra_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2019, 6, 30, 21, 39, 21, 89499))),
            ],
        ),
    ]
