# Generated by Django 2.2.1 on 2019-07-01 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0010_auto_20190630_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 30, 23, 35, 50, 716189)),
        ),
    ]
