# Generated by Django 2.2.1 on 2019-07-02 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0011_auto_20190630_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 22, 49, 2, 409711)),
        ),
    ]
