# Generated by Django 2.2.1 on 2019-07-02 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0013_auto_20190702_0043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registro_huesped',
        ),
    ]
