# Generated by Django 2.2.1 on 2019-07-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0014_delete_registro_huesped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huesped',
            name='run_huesped',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='huesped',
            table='MANTENEDOR_HUESPED',
        ),
    ]
