# Generated by Django 2.2.1 on 2019-07-02 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0013_auto_20190702_0222'),
        ('mantenedor', '0015_auto_20190702_0056'),
    ]

    operations = [
    ]
